// <auto-generated />
namespace Online_Medicine_Shopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class temoraryMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(temoraryMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202003271458159_temoraryMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
